-- DEONGEORI_GALLERY
-- 덩어리 갤러리 테이블.
-- DEONGEORI_JOIN_MEMBER 테이블을 참조합니다.
-- DEONGEORI_JOIN_MEMBER.DNG_ID, DNG_MEM_ID(1) : DEONGEORI_GALLERY.DNG_ID, DNG_GAL_WRITER(0, N)
-- 1. 해당 덩어리의 멤버만 갤러리에 이미지를 업로드 할 수 있습니다.

/* 인덱스 삭제 */
DROP INDEX SCOTT.PK_DEONGEORI_GALLERY;

/* 덩어리 갤러리 테이블 생성 */
DROP TABLE SCOTT.DEONGEORI_GALLERY 
	CASCADE CONSTRAINTS;

/* 덩어리 갤러리 테이블 삭제 */
CREATE TABLE SCOTT.DEONGEORI_GALLERY (
	DNG_ID VARCHAR2(15) NOT NULL, /* 덩어리 아이디 */
	DNG_GAL_ID INT NOT NULL, /* 이미지 번호 */
	DNG_GAL_WRITER VARCHAR2(15) NOT NULL, /* 이미지 올린이 */
	DNG_GAL_CONTENT VARCHAR2(300) NOT NULL, /* 이미지 설명 */
	DNG_GAL_PWD VARCHAR2(10) NOT NULL, /* 이미지 비밀번호 */
	DNG_GAL_LIKECOUNT INT DEFAULT 0, /* 이미지 좋아요 횟수 */
	DNG_GAL_IMG VARCHAR2(20) NOT NULL, /* 이미지  */
	DNG_GAL_REGDATE DATE NOT NULL /* 이미지 등록일시 */
);

/* 인덱스 생성 */
CREATE UNIQUE INDEX SCOTT.PK_DEONGEORI_GALLERY
	ON SCOTT.DEONGEORI_GALLERY (
		DNG_ID ASC,
		DNG_GAL_ID ASC
	);

/* 기본키 설정 */
ALTER TABLE SCOTT.DEONGEORI_GALLERY
	ADD
		CONSTRAINT PK_DEONGEORI_GALLERY
		PRIMARY KEY (
			DNG_ID,
			DNG_GAL_ID
		);

/* 테이블, 컬럼 주석 */	
COMMENT ON TABLE SCOTT.DEONGEORI_GALLERY IS '덩어리 갤러리 테이블.';

COMMENT ON COLUMN SCOTT.DEONGEORI_GALLERY.DNG_ID IS '어떤 덩어리의 이미지인가?';

COMMENT ON COLUMN SCOTT.DEONGEORI_GALLERY.DNG_GAL_ID IS '이미지 번호';

COMMENT ON COLUMN SCOTT.DEONGEORI_GALLERY.DNG_GAL_WRITER IS '이미지 올린이의 회원 아이디.';

COMMENT ON COLUMN SCOTT.DEONGEORI_GALLERY.DNG_GAL_CONTENT IS '간단한 이미지 설명.';

COMMENT ON COLUMN SCOTT.DEONGEORI_GALLERY.DNG_GAL_PWD IS '이미지 비밀번호';

COMMENT ON COLUMN SCOTT.DEONGEORI_GALLERY.DNG_GAL_LIKECOUNT IS '이미지 좋아요 횟수';

COMMENT ON COLUMN SCOTT.DEONGEORI_GALLERY.DNG_GAL_IMG IS 'g + System.currentTimeMillis().확장자';

COMMENT ON COLUMN SCOTT.DEONGEORI_GALLERY.DNG_GAL_REGDATE IS '이미지 등록일시';

/* 덩어리 갤러리 이미지 번호 시퀀스 삭제 */
DROP SEQUENCE dng_gal_seq;

/* 덩어리 갤러리 이미지 번호 시퀀스 생성 */
CREATE SEQUENCE dng_gal_seq INCREMENT BY 1 START WITH 1 NOCACHE;

/* 외래키 설정 */
/* 외래키 제약 조건이 만족되지 않으면, 데이터가 삽입되지 않습니다. */
/* 부분 테스트 시에는 제외 시켜 주는 것이 편합니다. */
ALTER TABLE SCOTT.DEONGEORI_GALLERY
	ADD
		CONSTRAINT FK_DJM_TO_DG
		FOREIGN KEY (
			DNG_ID,
			DNG_GAL_WRITER
		)
		REFERENCES SCOTT.DEONGEORI_JOIN_MEMBER (
			DNG_ID,
			DNG_MEM_ID
		);

select * from SCOTT.DEONGEORI_GALLERY;
