-- DEONGEORI_MEMBER 
-- 덩어리 서비스 회원 테이블.
-- 외래키가 적용되려면, 가장 먼저 생성되어야 합니다.

/* 인덱스 삭제 */
DROP INDEX SCOTT.PK_DEONGEORI_MEMBER;

/* 덩어리 서비스 회원 테이블 삭제 */
DROP TABLE SCOTT.DEONGEORI_MEMBER 
	CASCADE CONSTRAINTS;

/* 덩어리 서비스 회원 테이블 생성 */
CREATE TABLE SCOTT.DEONGEORI_MEMBER (
	DNG_MEM_ID VARCHAR2(15) NOT NULL, /* 회원 아이디 */
	DNG_MEM_EMAIL VARCHAR2(50) NOT NULL, /* 회원 이메일 주소 */
	DNG_MEM_PWD VARCHAR2(10) NOT NULL, /* 회원 비밀번호 */
	DNG_MEM_NAME VARCHAR2(20) NOT NULL, /* 회원 이름 */
	DNG_MEM_NICKNAME VARCHAR2(20) NOT NULL, /* 회원 별명 */
	DNG_MEM_IMG VARCHAR2(20), /* 회원 프로필 이미지 */
	DNG_MEM_REGDATE DATE NOT NULL /* 회원 가입일시 */
);

/* 인덱스 생성 */
CREATE UNIQUE INDEX SCOTT.PK_DEONGEORI_MEMBER
	ON SCOTT.DEONGEORI_MEMBER (
		DNG_MEM_ID ASC
	);

/* 기본키 설정 */	
ALTER TABLE SCOTT.DEONGEORI_MEMBER
	ADD
		CONSTRAINT PK_DEONGEORI_MEMBER
		PRIMARY KEY (
			DNG_MEM_ID
		);
		
/* 테이블, 컬럼 주석 */
COMMENT ON TABLE SCOTT.DEONGEORI_MEMBER IS '덩어리 서비스 회원 테이블.';

COMMENT ON COLUMN SCOTT.DEONGEORI_MEMBER.DNG_MEM_ID IS '14 자리 (m + System.currentTimeMillis())';

COMMENT ON COLUMN SCOTT.DEONGEORI_MEMBER.DNG_MEM_EMAIL IS '회원 이메일 주소';

COMMENT ON COLUMN SCOTT.DEONGEORI_MEMBER.DNG_MEM_PWD IS '회원 비밀번호';

COMMENT ON COLUMN SCOTT.DEONGEORI_MEMBER.DNG_MEM_NAME IS '회원 이름';

COMMENT ON COLUMN SCOTT.DEONGEORI_MEMBER.DNG_MEM_NICKNAME IS '회원 별명';

COMMENT ON COLUMN SCOTT.DEONGEORI_MEMBER.DNG_MEM_IMG IS '회원 아이디.확장자';

COMMENT ON COLUMN SCOTT.DEONGEORI_MEMBER.DNG_MEM_REGDATE IS '회원 가입일시';

select * from deongeori_member;
