-- DEONGEORI_BOARD
-- 덩어리 게시판 테이블.
-- DEONGEORI_JOIN_MEMBER 테이블을 참조합니다.
-- DEONGEORI_JOIN_MEMBER.DNG_ID, DNG_MEM_ID(1) : DEONGEORI_BOARD.DNG_ID, DNG_BOARD_WRITER(0, N)
-- 1. 해당 덩어리의 멤버만 게시판에 글을 작성할 수 있습니다.

/* 인덱스 삭제 */
DROP INDEX SCOTT.PK_DEONGEORI_BOARD;

/* 덩어리 게시판 테이블 삭제 */
DROP TABLE SCOTT.DEONGEORI_BOARD 
	CASCADE CONSTRAINTS;

/* 덩어리 게시판 테이블 생성 */
CREATE TABLE SCOTT.DEONGEORI_BOARD (
	DNG_ID VARCHAR2(15) NOT NULL, /* 덩어리 아이디 */
	DNG_BOARD_ID INT NOT NULL, /* 글 번호 */
	DNG_BOARD_WRITER VARCHAR2(15) NOT NULL, /* 글 작성자 */
	DNG_BOARD_CONTENT VARCHAR2(2000) NOT NULL, /* 글 내용 */
	DNG_BOARD_PWD VARCHAR2(10) NOT NULL, /* 글 비밀번호 */
	DNG_BOARD_LIKECOUNT INT DEFAULT 0, /* 글 좋아요 횟수 */
	DNG_BOARD_REGDATE DATE NOT NULL /* 글 등록일시 */
);

/* 인덱스 생성 */
CREATE UNIQUE INDEX SCOTT.PK_DEONGEORI_BOARD
	ON SCOTT.DEONGEORI_BOARD (
		DNG_ID ASC,
		DNG_BOARD_ID ASC
	);

/* 기본키 설정 */
ALTER TABLE SCOTT.DEONGEORI_BOARD
	ADD
		CONSTRAINT PK_DEONGEORI_BOARD
		PRIMARY KEY (
			DNG_ID,
			DNG_BOARD_ID
		);

/* 테이블, 컬럼 주석 */			
COMMENT ON TABLE SCOTT.DEONGEORI_BOARD IS '덩어리 게시판 테이블.';

COMMENT ON COLUMN SCOTT.DEONGEORI_BOARD.DNG_ID IS '어떤 덩어리의 글인가?';

COMMENT ON COLUMN SCOTT.DEONGEORI_BOARD.DNG_BOARD_ID IS '글 번호';

COMMENT ON COLUMN SCOTT.DEONGEORI_BOARD.DNG_BOARD_WRITER IS '글 작성자';

COMMENT ON COLUMN SCOTT.DEONGEORI_BOARD.DNG_BOARD_CONTENT IS '글 내용';

COMMENT ON COLUMN SCOTT.DEONGEORI_BOARD.DNG_BOARD_PWD IS '글 비밀번호';

COMMENT ON COLUMN SCOTT.DEONGEORI_BOARD.DNG_BOARD_LIKECOUNT IS '글 좋아요 횟수';

COMMENT ON COLUMN SCOTT.DEONGEORI_BOARD.DNG_BOARD_REGDATE IS '글 등록일시';

/* 덩어리 게시판 글 번호 시퀀스 삭제 */
DROP SEQUENCE dng_board_seq;

/* 덩어리 게시판 글 번호 시퀀스 생성 */
CREATE SEQUENCE dng_board_seq INCREMENT BY 1 START WITH 1 NOCACHE;

/* 외래키 설정 */
/* 외래키 제약 조건이 만족되지 않으면, 데이터가 삽입되지 않습니다. */
/* 부분 테스트 시에는 제외 시켜 주는 것이 편합니다. */
ALTER TABLE SCOTT.DEONGEORI_BOARD
	ADD
		CONSTRAINT FK_DJM_TO_DB
		FOREIGN KEY (
			DNG_ID,
			DNG_BOARD_WRITER
		)
		REFERENCES SCOTT.DEONGEORI_JOIN_MEMBER (
			DNG_ID,
			DNG_MEM_ID
		);

select * from DEOGEORI_BOARD;