-- DEONGEORI_JOIN_MEMBER
-- 회원의 덩어리 가입 정보 관리 테이블.
-- DEONGEORI,DEONGEORI_MEMBER 테이블을 참조합니다
-- DEONGEORI.DNG_ID(1) : DEONGEORI_JOIN_MEMBER.DNG_ID(1, N)
-- 1. 존재하는 덩어리에만 가입할 수 있습니다.
-- DEONGEORI_MEMBER.DNG_MEM_ID(1) : DEONGEORI_JOIN_MEMBER.DNG_MEM_ID(1, N)
-- 1. 덩어리 서비스의 회원은 한 개 이상 덩어리의 멤버여야 합니다.

/* 인덱스 삭제 */
DROP INDEX SCOTT.PK_DEONGEORI_JOIN_MEMBER;

/* 덩어리 가입 회원 테이블 삭제 */
DROP TABLE SCOTT.DEONGEORI_JOIN_MEMBER 
	CASCADE CONSTRAINTS;

/* 덩어리 가입 회원 테이블 생성 */
CREATE TABLE SCOTT.DEONGEORI_JOIN_MEMBER (
	DNG_ID VARCHAR2(15) NOT NULL, /* 덩어리 아이디 */
	DNG_MEM_ID VARCHAR2(15) NOT NULL, /* 회원 아이디 */
	DNG_MEM_JOINDATE DATE NOT NULL /* 덩어리 가입일시 */
);
/* 인덱스 생성 */
CREATE UNIQUE INDEX SCOTT.PK_DEONGEORI_JOIN_MEMBER
	ON SCOTT.DEONGEORI_JOIN_MEMBER (
		DNG_ID ASC,
		DNG_MEM_ID ASC
	);

/* 기본키 설정 */
ALTER TABLE SCOTT.DEONGEORI_JOIN_MEMBER
	ADD
		CONSTRAINT PK_DEONGEORI_JOIN_MEMBER
		PRIMARY KEY (
			DNG_ID,
			DNG_MEM_ID
		);

/* 테이블, 컬럼 주석 */
COMMENT ON TABLE SCOTT.DEONGEORI_JOIN_MEMBER IS '회원의 덩어리 가입 정보 테이블.';

COMMENT ON COLUMN SCOTT.DEONGEORI_JOIN_MEMBER.DNG_ID IS '회원이 가입한 덩어리 아이디.';

COMMENT ON COLUMN SCOTT.DEONGEORI_JOIN_MEMBER.DNG_MEM_ID IS '덩어리에 가입한 회원 아이디.';

COMMENT ON COLUMN SCOTT.DEONGEORI_JOIN_MEMBER.DNG_MEM_JOINDATE IS '덩어리 가입일시';

/* 외래키 설정 */
/* 외래키 제약 조건이 만족되지 않으면, 데이터가 삽입되지 않습니다. */
/* 부분 테스트 시에는 제외 시켜 주는 것이 편합니다. */
ALTER TABLE SCOTT.DEONGEORI_JOIN_MEMBER
	ADD
		CONSTRAINT FK_DEONGEORI_TO_DJM
		FOREIGN KEY (
			DNG_ID
		)
		REFERENCES SCOTT.DEONGEORI (
			DNG_ID
		);

ALTER TABLE SCOTT.DEONGEORI_JOIN_MEMBER
	ADD
		CONSTRAINT FK_DM_TO_DJM
		FOREIGN KEY (
			DNG_MEM_ID
		)
		REFERENCES SCOTT.DEONGEORI_MEMBER (
			DNG_MEM_ID
		);

